spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true

  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/**/
      file-extensions: .graphqls, .graphql
      printer:
        enabled: true