server:
  port: 9000
  servlet:
    context-path: /

spring:
  jpa:
    show-sql: true # 콘솔창에 SQL 출력
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
    properties:
      hibernate:
        format_sql: true # SQL 예쁘게 출력
        default_batch_fetch_size: 1000 # 일대다 컬렉션 조회 시 성능 최적화
